<?php

    $aa = "INSERT INTO your_table_name (name, discount_price, our_price, about_game, game_description, genre, multitags)
    VALUES
    ('Legends of Valor', $19.99, $29.99, 'Legends of Valor is an epic fantasy RPG where players embark on a quest to defeat an ancient evil threatening the realm. With a vast open world to explore, intricate quests to complete, and legendary loot to uncover, it promises adventure at every turn.', 'Players will create their hero, choosing from various classes and races, each with unique abilities and traits. As they journey through the land of Valor, they'll encounter mythical creatures, forge alliances with powerful factions, and ultimately face off against the dark forces threatening to plunge the world into chaos.', 'RPG, Fantasy', 'Adventure, Magic, Questing, Character Customization, Epic Battles'),
    ('Cybernetic Revolution', $14.99, $24.99, 'Cybernetic Revolution thrusts players into a dystopian future where technology has both empowered and enslaved humanity. As a member of the resistance, you must hack your way through corporate strongholds, uncovering the truth behind their oppressive regime.', 'With cutting-edge cybernetic enhancements, players navigate through neon-lit cityscapes, utilizing stealth, hacking skills, and combat prowess to dismantle the corrupt systems ruling society. Every choice made will shape the fate of the rebellion and determine the future of mankind.', 'Action, Adventure, Cyberpunk', 'Hacking, Futuristic, Rebellion, Stealth, Conspiracy'),
    ('Mythical Realms',$9.99, $14.99, 'Mythical Realms invites players into a world of enchantment and wonder, where ancient creatures roam and forgotten magic thrives. Set in a time of great upheaval, you must uncover the secrets of the past to shape the future of the realm.', 'With a rich narrative woven into every corner of the game world, players embark on a journey filled with perilous quests, intricate puzzles, and encounters with legendary beings. Whether forging alliances with noble knights or delving into the dark arts, the choices you make will determine the fate of the land.', 'Adventure, Puzzle, Fantasy', 'Magic, Exploration, Quests, Mysteries, Mythical Creatures'),
    ('Apex Chronicles: Galactic Conflict', 0.00, 0.00, 'Apex Chronicles: Galactic Conflict is a multiplayer shooter set in a sprawling sci-fi universe torn apart by war. Join forces with other players, customize your arsenal, and engage in intense battles across alien worlds in a fight for dominance.', 'As one of the elite soldiers of the Apex faction, you'll engage in fast-paced, team-based combat against rival factions vying for control of vital resources and territory. With a variety of game modes and constantly evolving content, every match offers new challenges and opportunities for glory.', 'Shooter, Multiplayer, Sci-Fi', 'Competitive, Team-based, Free-to-play, Space Warfare, Customization'),
    ('ChronoQuest: Time''s Reckoning', $29.99, $39.99, 'ChronoQuest: Time''s Reckoning is an epic time-traveling adventure where players must navigate the complexities of the temporal continuum to prevent a catastrophic event that threatens to unravel reality itself.', 'Armed with advanced chrono-tech, players journey across different eras, from ancient civilizations to distant futures, piecing together clues and altering key events to restore the balance of time. With a branching narrative and multiple endings, every decision has far-reaching consequences.', 'Adventure, Puzzle, Time Travel', 'Historical, Temporal Paradoxes, Narrative-driven, Puzzle-solving, Choices Matter'),
    ('Shadow''s Edge', $39.99, $49.99, 'Shadow''s Edge immerses players in a dark and treacherous world where ancient evils lurk in the shadows. As a lone hero, you must uncover the truth behind a mysterious curse that threatens to consume the land.', 'With a focus on intense combat and visceral action, players will face off against hordes of nightmarish creatures, mastering a variety of weapons and abilities to survive. Along the way, they'll uncover secrets hidden in the depths of the darkness and confront their own inner demons.', 'Action, Adventure, Horror', 'Dark Atmosphere, Monster Slaying, Exploration, Atmospheric, Character Progression'),
    ('Galactic Conquest', $24.99, $34.99, 'Galactic Conquest is a grand strategy game set in the vast expanse of space, where empires clash and civilizations rise and fall. Command fleets, forge alliances, and conquer worlds as you vie for dominance in the galaxy.', 'From managing your economy and researching new technologies to engaging in epic space battles and negotiating treaties with rival powers, every decision you make will shape the course of history. Will you lead your people to victory and establish a lasting legacy, or will you be consigned to the dustbin of history?', 'Strategy, Simulation, Sci-Fi', 'Empire Building, Diplomacy, Space Colonization, Tactical Warfare, Resource Management'),
    ('Mythical Odyssey', $14.99, $19.99, 'Mythical Odyssey is an action-packed adventure set in a world of gods and monsters, where heroes rise to challenge the divine and rewrite the myths of old.', 'With an emphasis on fast-paced combat and epic boss battles, players will journey through fantastical realms, battling legendary creatures and unraveling the mysteries of the ancient gods. Along the way, they'll forge their legend and claim their place among the pantheon of heroes.', 'Action, Adventure, Mythology', 'Gods and Monsters, Heroic Battles, Mythical Beasts, Legendary Quests, Ancient Relics'),
    ('Astral Frontier', $19.99, $29.99, 'Astral Frontier is a space RPG set in a distant galaxy where humanity struggles for survival against alien threats and political intrigue. As a captain of your own starship, you must navigate the dangers of the cosmos and carve out your destiny among the stars.', 'With a vast universe to explore, dynamic quests to complete, and factions to ally with or oppose, every decision you make will shape the fate of the galaxy. Will you be a hero of the people, a ruthless mercenary, or a cunning diplomat? The choice is yours.', 'RPG, Space, Adventure', 'Space Exploration, Intergalactic Warfare, Diplomacy, Questing, Alien Encounters'),
    ('Space Odyssey: Frontier Wars', $29.99, $39.99, 'Space Odyssey: Frontier Wars is a strategy game where players build and manage their own interstellar empire, conquering planets, researching new technologies, and engaging in epic space battles.', 'From humble beginnings on a single planet, players will expand their influence across the galaxy, colonizing new worlds, forging alliances, and waging war against rival factions. With multiple paths to victory and endless strategic possibilities, every game offers a new frontier to conquer.', 'Strategy, Simulation, Space', 'Empire Building, Space Colonization, Tactical Warfare, Resource Management, Technology'),
    ('Fabled Realms: Forgotten Legends', $14.99, $19.99, 'Fabled Realms: Forgotten Legends is a fantasy RPG where players embark on an epic quest to restore balance to a world torn apart by war and chaos. With a richly detailed world to explore, diverse characters to meet, and ancient secrets to uncover, it promises an unforgettable adventure.', 'As a hero chosen by fate, players will journey through sprawling cities, treacherous dungeons, and enchanted forests, facing off against powerful foes and making difficult choices that will shape the fate of the realm. With multiple endings and branching storylines, every playthrough offers new surprises and challenges.', 'RPG, Fantasy, Adventure', 'Magic, Questing, Epic Battles, Character Customization, Choices Matter'),
    ('Quantum Shift', $19.99, $29.99, 'Quantum Shift is a puzzle-platformer set in a world where the laws of physics are yours to bend. As a brilliant scientist trapped in a mysterious dimension, you must harness the power of quantum mechanics to escape and uncover the truth behind your predicament.', 'With mind-bending puzzles and gravity-defying platforming, players will explore surreal landscapes and manipulate reality itself to overcome obstacles and unlock new abilities. As they delve deeper into the secrets of the quantum realm, they'll unravel a story of betrayal, redemption, and the nature of reality itself.', 'Puzzle, Platformer, Adventure', 'Physics-based, Mind-bending, Puzzle-solving, Dimensional Travel, Narrative-driven'),
    ('Inferno's Fury', $39.99, $49.99, 'Inferno''s Fury is a dark fantasy RPG where players must navigate the treacherous depths of the underworld to uncover the truth behind a demonic invasion that threatens to consume the world above.', 'With a focus on visceral combat and strategic decision-making, players will journey through hellish landscapes, battling hordes of infernal creatures and forging alliances with powerful allies. Along the way, they'll uncover the secrets of their own past and confront the ultimate evil that lurks at the heart of the abyss.', 'RPG, Action, Adventure', 'Dark Atmosphere, Demons, Character Customization, Epic Battles, Mythical Beasts'),
    ('Skyward Odyssey', $24.99, $34.99, 'Skyward Odyssey is an open-world adventure game set in a fantastical realm where the sky is the limit. As a daring sky pirate, you must navigate the clouds, plunder ancient ruins, and battle rival crews to become the most notorious captain in the sky.', 'With a customizable airship at your command and a crew of loyal companions by your side, you'll explore floating islands, engage in aerial dogfights, and uncover hidden treasures in every corner of the sky. Along the way, you'll encounter mythical creatures, rival adventurers, and ancient guardians standing in your way to fortune and glory.', 'Adventure, Action, Fantasy', 'Pirates, Exploration, Airship Combat, Treasure Hunting, Open World'),
    ('Starborn Legacy', $14.99, $19.99, 'Starborn Legacy is a space opera RPG where players embark on an epic journey across the galaxy, forging alliances, battling ancient evils, and uncovering the secrets of a long-forgotten civilization.', 'As the captain of your own starship, you'll explore uncharted worlds, engage in ship-to-ship combat, and recruit a diverse crew of aliens, mercenaries, and outcasts to join your cause. With branching storylines and multiple endings, every decision you make will shape the fate of the galaxy and determine your legacy among the stars.', 'RPG, Space, Adventure', 'Space Exploration, Intergalactic Warfare, Diplomacy, Questing, Alien Encounters');

?>
